### ISSUE TITLE
Recipe 16 nonbinary error

### ISSUE THREAD

**Issue by bpulling** [hrbrmstr/21-recipes#10]
When running reciepe 16, even with the example of "juliasilge", I'm getting the output: "Error in x * scale : non-numeric argument to binary operator"

Any ideas?

**Comment by hrbrmstr** [comment]
#ty! for working though the exercises and for flagging this bug.

Turns out this line — https://github.com/hrbrmstr/21-recipes/blob/master/16-Crawling-Followers-to-Approximate-Potential-Influence.Rmd#L48 — used to have a `scales::comma()` wrapper around it which this line — https://github.com/hrbrmstr/21-recipes/blob/master/16-Crawling-Followers-to-Approximate-Potential-Influence.Rmd#L62 — really doesn't like.

It looks like the {scales} package became a bit more picky about inputs (which is a good thing).

I modified the function in the code and re-rendered the chapter — https://rud.is/books/21-recipes/crawling-followers-to-approximate-primary-influence.html

Again, many thanks for flagging this!

**Comment by bpulling** [comment]
This is an incredible resource, I'm still basically just learning R, but a phenomenal way to integrate practical analyses with coding, thank you for writing it, and responding!
